apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hlaingminpaing/monitoring-helm.git
    targetRevision: main
    path: alertmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true