apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hlaingminpaing/monitoring-helm.git
    targetRevision: main
    path: kube-prometheus-stack
    helm:
      # For kube-prometheus-stack
      releaseName: kube-prometheus-stack
      valueFiles:
        - kube-prometheus-stack/values.yaml
      # Reference other charts as subcharts/dependencies
      dependencies:
        - name: grafana
          version: "8.11.0"
          repository: "https://grafana.github.io/helm-charts"
        - name: kube-prometheus-stack
          version: "72.7.0"  # Specific version for stability
          repository: "https://prometheus-community.github.io/helm-charts"

      # Or use explicit helm parameters
      parameters:
        - name: "global.scrape_interval"
          value: "15s"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true