apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hlaingminpaing/monitoring-helm.git
    targetRevision: HEAD
    path: kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
      dependencies:
        - name: kube-prometheus-stack
          version: "72.7.0"
          repository: "https://prometheus-community.github.io/helm-charts"
      parameters:
        - name: "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName"
          value: "standard"
        - name: "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage"
          value: "10Gi"
        - name: "grafana.persistence.storageClassName"
          value: "standard"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true